<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="css/style.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script src="js/script.js" defer></script>
    <title><?= (isset($layoutTitle))?$layoutTitle:'To Do List' ?></title>
</head>

<body>
    <header>
        <!-- for burger menu in js-->
        <button class="burger-menu">
            <i class="fa-solid fa-bars"></i>
        </button>
        
        <nav>
            <a class="logo" href="index.php">3WA Tasks</a>
        </nav>
    </header>
    
    <main>
        <?php include $template; ?>
    </main>
    
    <footer>
        <p>&copy; 2026 - 3W Academy</p>
    </footer>
</body>
</html>
