<div class="role-signup">
    <h1>Register</h1>
    <p>Welcome in the world of perfect tasks priorization !</p>
</div>


<div class="signup">
    <div class="container-signup">
        <form action="signup.php" method="POST">
            <label for="username">Username</label>
            <input type="text" id="username" name="username" required>
            
            <label for="email">Email</label>
            <input type="email" id="email" name="email" required>
            
            <label for="password">Password</label>
            <input type="password" id="password" name="password" required>
            
            <button type="submit">Register</button>
        </form>
    </div>
</div>